import { useState, useEffect, useCallback } from 'react';
import { Send, Truck, Package, Clock, CheckCircle2, FileDown, Loader2, LayoutGrid, Filter } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import PageTransition from '../components/PageTransition';
import DeliveryForm from '../components/DeliveryForm';
import { apiGet, apiPut } from '../lib/api';

const PRIORITY_STYLE = {
  Normal: 'text-white/40',
  Urgent: 'text-amber-300',
  Express: 'text-violet-300',
};

function timeAgo(dateStr) {
  if (!dateStr) return '—';
  const diff = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  return `${Math.floor(hrs / 24)}d ago`;
}

function StatusBadge({ status }) {
  const styles = {
    Done: 'bg-emerald-500/15 text-emerald-200 border-emerald-400/25',
    Packed: 'bg-blue-500/15 text-blue-200 border-blue-400/25',
    Picking: 'bg-amber-500/15 text-amber-200 border-amber-400/25',
    Draft: 'bg-white/5 text-white/50 border-white/10',
  }[status] || 'bg-white/5 text-white/50 border-white/10';
  return (
    <span className={`text-xs font-semibold px-2.5 py-1 rounded-full border ${styles}`}>
      {status}
    </span>
  );
}

// ─── Generate delivery challan HTML ──────────────────────────────────────────
function generateChallanHTML(d) {
  const rows = (d.products || []).map((p) => `
    <tr>
      <td>${p.productId?.name || '—'}</td>
      <td>${p.productId?.sku || '—'}</td>
      <td>${p.productId?.unit || '—'}</td>
      <td style="text-align:right">${p.quantity}</td>
    </tr>`).join('');
  const priorityColor = d.priority === 'Urgent' ? '#f59e0b' : d.priority === 'Express' ? '#8b5cf6' : '#6b7280';
  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"/><title>Delivery Challan ${d._id?.slice(-6).toUpperCase()}</title>
<style>
  body{font-family:'Segoe UI',Arial,sans-serif;background:#fff;color:#111;padding:40px;max-width:720px;margin:auto}
  h1{font-size:26px;margin:0 0 4px;color:#1a1a2e}
  .sub{color:#666;font-size:13px;margin-bottom:24px}
  .meta{display:flex;gap:28px;margin-bottom:28px;flex-wrap:wrap}
  .meta label{font-size:11px;text-transform:uppercase;letter-spacing:.1em;color:#888}
  .meta p{margin:4px 0 0;font-weight:600;font-size:14px}
  table{width:100%;border-collapse:collapse;margin-top:8px}
  th{text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:#888;padding:8px 12px;border-bottom:2px solid #e5e7eb}
  td{padding:11px 12px;font-size:13px;border-bottom:1px solid #f0f0f0}
  .badge{display:inline-block;padding:3px 10px;border-radius:20px;font-size:11px;font-weight:700;background:#d1fae5;color:#065f46}
  .priority{display:inline-block;padding:3px 10px;border-radius:20px;font-size:11px;font-weight:700;color:${priorityColor};border:1px solid ${priorityColor}40}
  .footer{margin-top:32px;font-size:12px;color:#bbb;text-align:center;border-top:1px solid #e5e7eb;padding-top:16px}
  @media print{body{padding:20px}}
</style>
</head>
<body>
  <h1>INVENFLOW Delivery Challan</h1>
  <div class="sub">Outgoing Shipment / Delivery Order</div>
  <div class="meta">
    <div><label>Challan ID</label><p>#${d._id?.slice(-6).toUpperCase()}</p></div>
    <div><label>Customer</label><p>${d.customerName || '—'}</p></div>
    <div><label>Status</label><p><span class="badge">${d.status}</span></p></div>
    <div><label>Priority</label><p><span class="priority">${d.priority || 'Normal'}</span></p></div>
    <div><label>Date</label><p>${new Date(d.createdAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</p></div>
    ${d.expectedDate ? `<div><label>Expected</label><p>${new Date(d.expectedDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</p></div>` : ''}
    ${d.notes ? `<div><label>Notes</label><p>${d.notes}</p></div>` : ''}
  </div>
  <table>
    <thead><tr><th>Product</th><th>SKU</th><th>Unit</th><th style="text-align:right">Qty</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="footer">Generated by INVENFLOW · ${new Date().toLocaleString()}</div>
</body></html>`;
}

async function downloadChallan(deliveryId) {
  const token = localStorage.getItem('ims_token');
  const res = await fetch(`/api/deliveries/${deliveryId}`, { headers: { Authorization: `Bearer ${token}` } });
  if (!res.ok) throw new Error('Failed to fetch delivery');
  const data = await res.json();
  const win = window.open('', '_blank');
  win.document.write(generateChallanHTML(data.delivery));
  win.document.close();
  setTimeout(() => win.print(), 400);
}

const STATUS_FILTERS = ['All', 'Draft', 'Picking', 'Packed', 'Done'];

export default function Deliveries() {
  const [deliveries, setDeliveries] = useState([]);
  const [filter, setFilter] = useState('All');
  const [validating, setValidating] = useState(null);
  const [downloading, setDownloading] = useState(null);

  const load = useCallback(() => {
    apiGet('/deliveries?limit=50')
      .then((data) => {
        const list = data.deliveries || data || [];
        setDeliveries(list.map((d) => ({
          _id: d._id,
          id: d._id?.slice(-6).toUpperCase() || '—',
          customer: d.customerName,
          items: d.products?.length || 0,
          status: d.status,
          priority: d.priority || 'Normal',
          time: timeAgo(d.createdAt),
        })));
      })
      .catch(() => {});
  }, []);

  useEffect(() => { load(); }, [load]);

  const stats = {
    total: deliveries.length,
    draft: deliveries.filter((d) => d.status === 'Draft').length,
    done: deliveries.filter((d) => d.status === 'Done').length,
    urgent: deliveries.filter((d) => d.priority === 'Urgent' || d.priority === 'Express').length,
  };

  const visible = filter === 'All' ? deliveries : deliveries.filter((d) => d.status === filter);

  const quickValidate = async (id) => {
    setValidating(id);
    try {
      await apiPut(`/deliveries/${id}/validate`, {});
      load();
    } catch (e) {
      alert('Validation failed: ' + e.message);
    } finally {
      setValidating(null);
    }
  };

  const handleDownload = async (deliveryId) => {
    setDownloading(deliveryId);
    try { await downloadChallan(deliveryId); }
    catch (e) { alert('Download failed: ' + e.message); }
    finally { setDownloading(null); }
  };

  return (
    <PageTransition>
      {/* Header */}
      <header className="glass-card glow-border rounded-[24px] p-5 sm:p-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-white/60">
            <Send className="w-5 h-5" />
            <span className="text-xs uppercase tracking-[0.2em]">Outgoing</span>
          </div>
          <h2 className="text-3xl font-black text-white mt-1 neon-text">Deliveries</h2>
          <p className="text-white/60">Validate shipments and prevent negative stock</p>
        </div>
        {/* Stats chips */}
        <div className="flex flex-wrap gap-2">
          {[
            { label: 'Total', val: stats.total, cls: 'bg-white/5 text-white/60 border-white/10' },
            { label: 'Draft', val: stats.draft, cls: 'bg-amber-500/10 text-amber-200 border-amber-400/20' },
            { label: 'Done', val: stats.done, cls: 'bg-emerald-500/10 text-emerald-200 border-emerald-400/20' },
            { label: 'Priority', val: stats.urgent, cls: 'bg-violet-500/10 text-violet-200 border-violet-400/20' },
          ].map((s) => (
            <div key={s.label} className={`px-3 py-1.5 rounded-xl border text-xs font-semibold ${s.cls}`}>
              {s.val} {s.label}
            </div>
          ))}
        </div>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
        {/* Form */}
        <div className="lg:col-span-2">
          <DeliveryForm onCreated={load} />
        </div>

        {/* Deliveries list */}
        <div className="lg:col-span-3 glass-card glow-border rounded-[24px] p-5 space-y-4">
          <div className="flex items-center justify-between gap-3 flex-wrap">
            <div className="flex items-center gap-2 text-white/70">
              <Truck className="w-5 h-5" />
              <span className="font-semibold">Delivery Queue</span>
            </div>
            {/* Status filter tabs */}
            <div className="flex items-center gap-1 bg-white/5 rounded-xl p-1 border border-white/8">
              <Filter className="w-3.5 h-3.5 text-white/30 ml-1.5" />
              {STATUS_FILTERS.map((s) => (
                <button
                  key={s}
                  onClick={() => setFilter(s)}
                  className={`px-2.5 py-1 rounded-lg text-xs font-semibold transition-all ${
                    filter === s
                      ? 'bg-violet-500/30 text-violet-200 border border-violet-400/30'
                      : 'text-white/35 hover:text-white/60'
                  }`}
                >
                  {s}
                </button>
              ))}
            </div>
          </div>

          <div className="divide-y divide-white/8">
            {visible.length === 0 && (
              <div className="flex flex-col items-center gap-3 py-12 text-center">
                <LayoutGrid className="w-10 h-10 text-white/10" />
                <p className="text-white/25 text-sm">No deliveries {filter !== 'All' ? `with status "${filter}"` : 'yet'}</p>
              </div>
            )}
            <AnimatePresence>
              {visible.map((item, idx) => (
                <motion.div
                  key={item._id}
                  initial={{ opacity: 0, y: 6 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  transition={{ delay: idx * 0.04 }}
                  className="flex items-center gap-3 py-3.5"
                >
                  {/* Icon */}
                  <div className="w-9 h-9 rounded-xl bg-cyan-500/12 border border-cyan-400/18 flex items-center justify-center shrink-0">
                    <Package className="w-4.5 h-4.5 text-cyan-200" />
                  </div>
                  {/* Info */}
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-semibold text-white truncate leading-tight">{item.customer}</p>
                    <div className="flex items-center gap-2 mt-0.5">
                      <span className="text-xs text-white/35 font-mono">{item.id}</span>
                      {item.priority !== 'Normal' && (
                        <span className={`text-xs font-bold ${PRIORITY_STYLE[item.priority]}`}>{item.priority === 'Urgent' ? '⚡' : '🚀'} {item.priority}</span>
                      )}
                    </div>
                  </div>
                  {/* Meta */}
                  <div className="flex items-center gap-2 shrink-0 flex-wrap justify-end">
                    <span className="text-white/30 flex items-center gap-1 text-xs">
                      <Clock className="w-3 h-3" /> {item.time}
                    </span>
                    <StatusBadge status={item.status} />
                    <span className="text-white/30 text-xs">{item.items} items</span>

                    {/* Quick validate for Draft */}
                    {item.status === 'Draft' && (
                      <button
                        title="Validate & dispatch"
                        onClick={() => quickValidate(item._id)}
                        disabled={!!validating}
                        className="w-8 h-8 rounded-xl bg-emerald-500/12 hover:bg-emerald-500/25 border border-emerald-400/20 flex items-center justify-center text-emerald-300/50 hover:text-emerald-300 transition-all disabled:opacity-40"
                      >
                        {validating === item._id
                          ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
                          : <CheckCircle2 className="w-3.5 h-3.5" />}
                      </button>
                    )}

                    {/* Download challan */}
                    <button
                      title="Download delivery challan"
                      onClick={() => handleDownload(item._id)}
                      disabled={!!downloading}
                      className="w-8 h-8 rounded-xl bg-white/5 hover:bg-violet-500/18 border border-white/10 hover:border-violet-400/28 flex items-center justify-center text-white/30 hover:text-violet-300 transition-all disabled:opacity-40"
                    >
                      {downloading === item._id
                        ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
                        : <FileDown className="w-3.5 h-3.5" />}
                    </button>
                  </div>
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        </div>
      </div>
    </PageTransition>
  );
}

