import { useState, useEffect } from 'react';
import { ClipboardList, ArrowDownCircle, Package, Clock, Download, FileDown, Loader2 } from 'lucide-react';
import PageTransition from '../components/PageTransition';
import ReceiptForm from '../components/ReceiptForm';
import { motion } from 'framer-motion';
import { apiGet } from '../lib/api';

// ─── Generate printable receipt HTML ─────────────────────────────────────────
function generateReceiptHTML(r) {
  const rows = (r.products || []).map(p => `
    <tr>
      <td>${p.productId?.name || '—'}</td>
      <td>${p.productId?.sku || '—'}</td>
      <td>${p.productId?.unit || '—'}</td>
      <td style="text-align:right">${p.quantity}</td>
    </tr>`).join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>Receipt ${r._id?.slice(-6).toUpperCase()}</title>
  <style>
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #fff; color: #111; padding: 40px; max-width: 700px; margin: auto; }
    h1 { font-size: 28px; margin: 0 0 4px; color: #1a1a2e; }
    .sub { color: #666; font-size: 13px; margin-bottom: 24px; }
    .meta { display: flex; gap: 32px; margin-bottom: 28px; flex-wrap: wrap; }
    .meta div { }
    .meta label { font-size: 11px; text-transform: uppercase; letter-spacing: .1em; color: #888; }
    .meta p { margin: 4px 0 0; font-weight: 600; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: .08em; color: #888; padding: 8px 12px; border-bottom: 2px solid #e5e7eb; }
    td { padding: 12px 12px; font-size: 13px; border-bottom: 1px solid #f0f0f0; }
    .badge { display: inline-block; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 700;
      background: ${r.status === 'Done' ? '#d1fae5' : '#fef3c7'}; color: ${r.status === 'Done' ? '#065f46' : '#92400e'}; }
    .footer { margin-top: 32px; font-size: 12px; color: #bbb; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 16px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>INVENFLOW Receipt</h1>
  <div class="sub">Purchase Receipt / Goods Received Note</div>
  <div class="meta">
    <div><label>Receipt ID</label><p>#${r._id?.slice(-6).toUpperCase()}</p></div>
    <div><label>Supplier</label><p>${r.supplierName || '—'}</p></div>
    <div><label>Status</label><p><span class="badge">${r.status}</span></p></div>
    <div><label>Date</label><p>${new Date(r.createdAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })}</p></div>
    <div><label>Items</label><p>${r.products?.length || 0} product(s)</p></div>
  </div>
  <table>
    <thead><tr><th>Product</th><th>SKU</th><th>Unit</th><th style="text-align:right">Qty</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="footer">Generated by INVENFLOW · ${new Date().toLocaleString()}</div>
</body>
</html>`;
}

// ─── Download single receipt ──────────────────────────────────────────────────
async function downloadReceipt(receiptId, format = 'print') {
  const token = localStorage.getItem('ims_token');
  const res = await fetch(`/api/receipts/${receiptId}`, { headers: { Authorization: `Bearer ${token}` } });
  if (!res.ok) throw new Error('Failed to fetch receipt');
  const data = await res.json();
  const r = data.receipt;

  if (format === 'csv') {
    const rows = [
      ['Receipt ID', 'Supplier', 'Status', 'Date', 'Product', 'SKU', 'Unit', 'Qty'],
      ...(r.products || []).map(p => [
        r._id?.slice(-6).toUpperCase(), r.supplierName, r.status,
        new Date(r.createdAt).toLocaleDateString(),
        p.productId?.name || '—', p.productId?.sku || '—', p.productId?.unit || '—', p.quantity,
      ]),
    ];
    const csv = rows.map(r => r.map(c => `"${c}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a'); a.href = url; a.download = `receipt-${r._id?.slice(-6)}.csv`; a.click();
    URL.revokeObjectURL(url);
  } else {
    const html = generateReceiptHTML(r);
    const win = window.open('', '_blank');
    win.document.write(html);
    win.document.close();
    setTimeout(() => win.print(), 400);
  }
}

// ─── Export all receipts as CSV ───────────────────────────────────────────────
async function exportAllCSV() {
  const token = localStorage.getItem('ims_token');
  const res = await fetch('/api/receipts?limit=10000', { headers: { Authorization: `Bearer ${token}` } });
  const data = await res.json();
  const receipts = data.receipts || [];
  const rows = [
    ['Receipt ID', 'Supplier', 'Status', 'Date', 'Items'],
    ...receipts.map(r => [
      r._id?.slice(-6).toUpperCase(), r.supplierName, r.status,
      new Date(r.createdAt).toLocaleDateString(), r.products?.length || 0,
    ]),
  ];
  const csv = rows.map(r => r.map(c => `"${c}"`).join(',')).join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a'); a.href = url; a.download = 'receipts.csv'; a.click();
  URL.revokeObjectURL(url);
}

export default function Receipts() {
  const [recent, setRecent] = useState([]);
  const [downloading, setDownloading] = useState(null);

  const load = () => {
    apiGet('/receipts')
      .then((data) => {
        const list = data.receipts || data || [];
        setRecent(
          list.slice(0, 20).map((r) => ({
            _id: r._id,
            id: r._id?.slice(-6).toUpperCase() || '—',
            supplier: r.supplierName,
            items: r.products?.length || 0,
            status: r.status,
            time: timeAgo(r.createdAt),
          }))
        );
      })
      .catch(() => {});
  };

  useEffect(() => { load(); }, []);

  const handleDownload = async (receiptId, format) => {
    setDownloading(receiptId + format);
    try { await downloadReceipt(receiptId, format); }
    catch (e) { alert('Download failed: ' + e.message); }
    finally { setDownloading(null); }
  };

  return (
    <PageTransition>
      <header className="glass-card glow-border rounded-[24px] p-5 sm:p-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-white/60">
            <ClipboardList className="w-5 h-5" />
            <span className="text-xs uppercase tracking-[0.2em]">Incoming</span>
          </div>
          <h2 className="text-3xl font-black text-white mt-1 neon-text">Receipts</h2>
          <p className="text-white/60">Log inbound stock and update inventory</p>
        </div>
        <button
          onClick={exportAllCSV}
          className="flex items-center gap-2 px-4 py-3 rounded-2xl btn-primary text-sm font-semibold"
        >
          <FileDown className="w-4 h-4" />
          Export All CSV
        </button>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
        <div className="lg:col-span-2">
          <ReceiptForm onCreated={load} />
        </div>
        <div className="lg:col-span-3 glass-card glow-border rounded-[24px] p-5 space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-white/70">
              <ArrowDownCircle className="w-5 h-5" />
              <span className="font-semibold">Recent Receipts</span>
            </div>
            <span className="text-xs text-white/50">Auto-updated</span>
          </div>

          <div className="divide-y divide-white/10">
            {recent.length === 0 && (
              <p className="text-center py-8 text-white/30 text-sm">No receipts yet</p>
            )}
            {recent.map((item, idx) => (
              <motion.div
                key={item.id}
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.05 }}
                className="flex items-center justify-between py-4 gap-3"
              >
                <div className="flex items-center gap-3 min-w-0 flex-1">
                  <div className="w-10 h-10 rounded-2xl bg-emerald-500/15 border border-emerald-400/20 flex items-center justify-center shrink-0">
                    <Package className="w-5 h-5 text-emerald-200" />
                  </div>
                  <div className="min-w-0">
                    <p className="text-sm font-semibold text-white truncate">{item.supplier}</p>
                    <p className="text-xs text-white/50 font-mono">{item.id}</p>
                  </div>
                </div>
                <div className="flex items-center gap-3 text-sm shrink-0 flex-wrap justify-end">
                  <span className="text-white/50 flex items-center gap-1 text-xs">
                    <Clock className="w-3.5 h-3.5" /> {item.time}
                  </span>
                  <StatusBadge status={item.status} />
                  <span className="text-white/50 text-xs">{item.items} items</span>
                  {/* Download buttons */}
                  <div className="flex items-center gap-1.5">
                    <button
                      title="Print / Save as PDF"
                      onClick={() => handleDownload(item._id, 'print')}
                      disabled={!!downloading}
                      className="w-8 h-8 rounded-xl bg-white/5 hover:bg-violet-500/20 border border-white/10 hover:border-violet-400/30 flex items-center justify-center text-white/40 hover:text-violet-300 transition-all disabled:opacity-40"
                    >
                      {downloading === item._id + 'print' ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Download className="w-3.5 h-3.5" />}
                    </button>
                    <button
                      title="Download as CSV"
                      onClick={() => handleDownload(item._id, 'csv')}
                      disabled={!!downloading}
                      className="w-8 h-8 rounded-xl bg-white/5 hover:bg-cyan-500/20 border border-white/10 hover:border-cyan-400/30 flex items-center justify-center text-white/40 hover:text-cyan-300 transition-all disabled:opacity-40"
                    >
                      {downloading === item._id + 'csv' ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <FileDown className="w-3.5 h-3.5" />}
                    </button>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </PageTransition>
  );
}

function StatusBadge({ status }) {
  const styles = {
    Done: 'bg-emerald-500/15 text-emerald-200 border-emerald-400/25',
    Waiting: 'bg-amber-500/15 text-amber-200 border-amber-400/25',
    Draft: 'bg-white/5 text-white/60 border-white/10',
  }[status] || 'bg-white/5 text-white/60 border-white/10';
  return (
    <span className={`text-xs font-semibold px-3 py-1 rounded-full border ${styles}`}>
      {status}
    </span>
  );
}

function timeAgo(dateStr) {
  if (!dateStr) return '—';
  const diff = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  return `${Math.floor(hrs / 24)}d ago`;
}
